### ISSUE TITLE
Issue with setting up Demo

### ISSUE THREAD

**Issue by YasirKusay** [adRn-s/parkour2#59]
Hi, I ran make to setup a Demo environment but I was hit with this error. Could you help me with this?

[+] Running 5/5
 ✔ parkour2-caddy 4 layers [⣿⣿⣿⣿]      0B/0B      Pulled                  11.0s 
   ✔ 7264a8db6415 Pull complete                                            1.7s 
   ✔ e0aa7b81ef11 Pull complete                                            1.8s 
   ✔ 29b3b3e68e52 Pull complete                                            2.4s 
   ✔ a9c55d325954 Pull complete                                            3.7s 
WARN[0011] Found orphan containers ([parkour2-django parkour2-postgres]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 3/3
 ✔ Volume "parkour2_caddy_data"    Creat...                                0.0s 
 ✔ Volume "parkour2_caddy_config"  Cre...                                  0.0s 
 ✔ Container parkour2-caddy        Started                                 0.5s 
/usr/local/lib/python3.11/site-packages/django/http/request.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
/usr/local/lib/python3.11/site-packages/django/utils/encoding.py:266: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  encoding = locale.getdefaultlocale()[1] or 'ascii'

7872 static files copied to '/usr/src/app/staticfiles'.
/usr/local/lib/python3.11/site-packages/django/http/request.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  import cgi
/usr/local/lib/python3.11/site-packages/django/utils/encoding.py:266: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  encoding = locale.getdefaultlocale()[1] or 'ascii'
SELECT "invoicing_librarypreparationcosts"."id", "invoicing_librarypreparationcosts"."library_protocol_id", "invoicing_librarypreparationcosts"."price" FROM "invoicing_librarypreparationcosts" INNER JOIN "library_sample_shared_libraryprotocol" ON ("invoicing_librarypreparationcosts"."library_protocol_id" = "library_sample_shared_libraryprotocol"."id") WHERE "library_sample_shared_libraryprotocol"."obsolete" = 1
	 Processing: common/fixtures/organization.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "common_organization" does not exist
LINE 1: UPDATE "common_organization" SET "name" = 'DEEP' WHERE "comm...
               ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/common/management/commands/load_initial_data.py", line 10, in handle
    self.load_common_fixtures()
  File "/usr/src/app/common/management/commands/load_initial_data.py", line 24, in load_common_fixtures
    self.loaddata_wrapper(model="organization", app_label="common")
  File "/usr/src/app/common/management/commands/load_initial_data.py", line 21, in loaddata_wrapper
    call_command("loaddata", model, app_label=app_label)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.11/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: Problem installing fixture '/usr/src/app/common/fixtures/organization.json': Could not load common.Organization(pk=1): relation "common_organization" does not exist
LINE 1: UPDATE "common_organization" SET "name" = 'DEEP' WHERE "comm...
               ^

make: *** [Makefile:175: load-fixtures] Error 1

**Comment by adRn-s** [comment]
Thanks for the report! I will fix it asap. In the meantime, you may run `make schema load-fixtures` after the error, this 'schema' step is missing because of some changes we did. After that, you'll be able to follow the instructions as per the Wiki.
